wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/intro.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/blume.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/bouda.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/carl.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/chiarcos.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/declerck.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/eckart.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/hellmann.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/herold.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/lewis.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/llod.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/mccrae.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/moran.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/nordhoff.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/owlg.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/pareja.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/schalley.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/vanerp.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/windhouwer.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/ldl.bib
cd slides/
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/slides/blume_slides.pptx
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/slides/bouda_slides.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/slides/carl_slides.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/slides/declerck_slides.ppt
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/slides/eckart_slides.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/slides/herold_slides.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/slides/mccrae_slides.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/slides/moran_slides.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/slides/pareja_slides.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/slides/schalley_slides.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/slides/van_erp_slides.pdf
wget http://svn.aksw.org/papers/2012/LDL/ldl2012_proceedings/public/slides/windhouwer_slides.pptx
